fields_to_sort_clients = [
    "NombreCliente",
    "CodigoCliente",
    "Telefono",
    "Telefono2",
    "EMail1",
    "EMail2",
    "web",
    "Domicilio",
    "Municipio",
    "ComunidadAutonoma",
    "CodigoPostal",
    "Comercial",
    "Tarifa",
    "FormadePago",
    "CifDni",
    "IBAN",
    "FechaAlta",
    "Comentarios",
]

fields_to_sort_articles = [
    "NombreArticulo",
    "Descripcion",
    "CodigoArticulo",
    "PrecioVenta",
    "PrecioCompra",
    "Stock",
    "Proveedor",
    "Marca",
    "Familia",
    "CodigoBarras",
    "CodigoAlternativo",
]

MESES = [
    "Ene",
    "Feb",
    "Mar",
    "Abr",
    "May",
    "Jun",
    "Jul",
    "Ago",
    "Sep",
    "Oct",
    "Nov",
    "Dic",
]
